services:
  postgres:
    image: postgres:15-alpine
    container_name: cube_crush_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/database_schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cube-crush-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  eureka-server:
    build: ./backend/eureka-server
    container_name: cube_crush_eureka
    # ports:
    #   - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - cube-crush-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8761/"]
      interval: 30s
      timeout: 10s
      retries: 3

  api-gateway:
    build: ./backend/api-gateway
    container_name: cube_crush_gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=docker
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - cube-crush-network

  auth-service:
    build: ./backend/auth-service
    container_name: cube_crush_auth
    # ports:
    #   - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_PROFILES_ACTIVE=docker
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      eureka-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - cube-crush-network

  user-service:
    # ports:
    #   - "8082:8082"
    build: ./backend/user-service
    container_name: cube_crush_user
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      eureka-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - cube-crush-network

  game-service:
    # ports:
    #   - "8083:8083"
    build: ./backend/game-service
    container_name: cube_crush_game
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      eureka-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - cube-crush-network

volumes:
  postgres_data:

networks:
  cube-crush-network:
    driver: bridge
